language: bash
services: docker

matrix:
  include:
    - os: linux
      env: VERSION=1.12 VARIANT=alpine3.9

before_script:
  - env | sort
  - cd "$VERSION${VARIANT:+/$VARIANT}"
  - slash='/'; image="grahamar/go-dep:$VERSION${VARIANT:+-${VARIANT//$slash/-}}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )
after_script:
  - docker images

# vim:set et ts=2 sw=2: